### PR TITLE
Add JoeMarriage and Joe's Horse Collect

### PR DESCRIPTION
**Pull request by Bayside308**

### CODE REVIEW

**Comment by lukechatton** [comment]
Remove the comma you have on the last line. The last json object in a list shouldn't end with a comma.

**Comment by Bayside308** [comment]
Fixed, sorry. Do I make another Pull request?

**Comment by lukechatton** [comment]
nope :)

**Comment by Bayside308** [comment]
Ok, thanks! I was just wondering if you still plan on making a post about
3rd party servers. I am interested in adding mine to the list.

**Pull request merged**
