### PR TITLE
Add "Log"

### PR DESCRIPTION
**Pull request by Bayside308**
Log blocks in your world without MySQL or configuration.

This is one of my own plugins, and can be found [here](http://dev.bukkit.org/bukkit-plugins/total-block-logger/) on Bukkit. It should help player server staff deal with griefers easily, and doesn't require any configuration to work. Staff can clear the database on their own without need for file access (/log purge).

Thanks for the read!

### CODE REVIEW

**Comment by MODKILLER1001** [comment]
It will take too much ram I think

**Comment by Bayside308** [comment]
Trust me, it's the most light weight plugin for block logging. I
specifically made changes to lighten the load for servers. It doesn't store
data for rollbacks, etc. for that reason.

**Comment by imAero** [comment]
On the main page for your plugin, you say that **blocking placing and breaking is logged**. How big of a file would it end up being if you have any ideas?

**Comment by Bayside308** [comment]
It doesn't get very big since it isn't storing rollback data, stores block
IDs instead of names, etc. I'll run some tests and let you know. I'll break
1,000 blocks as a benchmark.

**Comment by Bayside308** [comment]
@imAero 

I just ran a test with 1k block edits, 500 places and 500 breaks. Information about the server [here](http://prntscr.com/bxbn4o). The server was run on my (old) PC with 768mb of RAM, and worked fine. The TPS were in the 19 range (As shown in the screenshot).

After 1k edits, the database size was 53kb.

**Comment by Bayside308** [comment]
[Here are some timings from the test server, focusing just on Log](http://prntscr.com/bxbpxi).

**Comment by imAero** [comment]
Discussed this with @tricksdash and we're going to set it as a T3 (tier 3) plugin. Could you possibly add `"requiredRank": "3"` to the end of your plugin in the plugins.json file? Make sure to put a comma at the end `configName` too.

**Comment by lukechatton** [comment]
By adding your plugin to our repo, you are accepting to our terms of use. If you would still like to have your plugin added, please reply here.

Our main concern with adding this for all users is that log files can quickly grow over weeks of time. Minehut's framework relies on being able to transfer files quickly.

**Comment by Bayside308** [comment]
Go ahead and add it :)

Thanks!

**Comment by Bayside308** [comment]
Fixed @imAero

**Pull request merged**
