### PR TITLE
add WarpPortals

### PR DESCRIPTION
**Pull request by MODKILLER1001**

### CODE REVIEW

**Comment by MODKILLER1001** [comment]
@lukechatton @imAero

**Comment by imAero** [comment]
Can't people just use Essentials warps?

**Comment by imAero** [comment]
@MODKILLER1001

**Comment by MODKILLER1001** [comment]
it uses portals to warp and people dont need perms to use them

**Comment by imAero** [comment]
I've seen people use command blocks for this type of portal idea. If it isn't much of a hassle you should probably do that. I feel that another plugin with a more important function would end up taking this plugin's place if it was added.

**Pull request closed without merging**
